version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=linebot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./linebot:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=linebot_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=secret_key
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    logging:
      driver: none
